import { Slide } from "./types";

export const slides: Slide[] = [
  // ============================================================
  // OPENING SECTION
  // ============================================================
  {
    id: 1,
    title: "How to Ship AI Slop into Production",
    content: "",
    type: "cover",
  },

  {
    id: 2,
    title: "Hi, I'm Naufaldi Rafif Satriya",
    content: `Senior Software Engineer at FMCG Company

**8 Years Experience in Software Development**

TypeScript, JavaScript • React, Next.js, Node.js`,
    type: "title",
  },

  {
    id: 3,
    title: "My AI Journey",
    content: `## 8 Months of Vibe Coding Experience

**Tools:** Cursor, Windsurf (Agent Harness)

**Models:** Anthropic Claude, Gemini, GPT, MiniMax

**Techniques:** BMAD, Beads, Plan Mode, Build Mode`,
    type: "content",
  },

  // ============================================================
  // PROBLEM DEFINITION
  // ============================================================
  {
    id: 4,
    title: "What is Slop?",
    content: "",
    type: "section",
  },

  {
    id: 5,
    title: "Slop Code Characteristics",
    content: `## What is Slop?

- Bad code that doesn't work as expected
- Hard to read and maintain
- Possibility of bugs (Security, Performance, etc.)
- Technical debt accumulation`,
    type: "content",
  },

  {
    id: 6,
    title: "AI Slop",
    content: "",
    type: "section",
  },

  {
    id: 7,
    title: "AI Slop Characteristics",
    content: `## AI Slop

- Code generated by AI with low quality
- Not working as expected
- Hard to read and maintain
- Bugs everywhere (Security, Performance, etc.)`,
    type: "content",
  },

  {
    id: 8,
    title: "Does this AI Slop?",
    content: `## Let's Look at Some Examples

We'll review 4 examples of bad code.

Can you spot which ones were written by AI?`,
    type: "content",
  },

  {
    id: 9,
    title: "Example 1: Bad Code",
    content: `![Example 1: Bad Code](/bad-code-1.webp)

**Meaningless constants** - Creating constants like \`ONE = 1\` adds no semantic value and defeats the purpose of constants`,
    type: "image",
  },

  {
    id: 10,
    title: "Example 2: Bad Code",
    content: `![Example 2: Bad Code](/bad-code-2.webp)

**Pyramid of doom** - Deeply nested if-else statements make code unreadable and hard to maintain`,
    type: "image",
  },

  {
    id: 11,
    title: "Example 3: Bad Code",
    content: `![Example 3: Bad Code](/bad-code-3.png)

**Extreme over-engineering** - Creating O(n²) complexity to generate one random number with unreadable nested indexing`,
    type: "image",
  },

  {
    id: 12,
    title: "Example 4: Bad Code",
    content: `![Example 4: Bad Code](/bad-code-4.webp)

**Ternary hell** - 15+ levels of nested ternary operators that should be handled with CSS media queries`,
    type: "image",
  },

  // ============================================================
  // THE REVEAL
  // ============================================================
  {
    id: 13,
    title: "That's Not AI Slop",
    content: "",
    type: "section",
  },

  {
    id: 14,
    title: "That's Engineer Slop",
    content: `## The Truth

- Before AI, engineers wrote code with low quality
- AI learned from engineer code
- Not every engineer can write good code
- Even senior engineers can write bad code

**AI didn't invent bad code. We did.**`,
    type: "content",
  },

  {
    id: 15,
    title: "The Reality",
    content: `## Slop Code

> "Slop Code existed before AI.
> 
> AI just embraced it."

AI models are trained on our code—the good, the bad, and the ugly.`,
    type: "quote",
  },

  {
    id: 16,
    title: "Questions to Consider",
    content: `## Think About This

**How to Ship AI Slop?**

**Why Ship Slop Code in the first place?**

*These are the wrong questions...*`,
    type: "content",
  },

  // ============================================================
  // SOLUTION: GUARDRAILS
  // ============================================================
  {
    id: 17,
    title: "Guardrails = Engineering Culture",
    content: "",
    type: "section",
  },

  {
    id: 18,
    title: "Three Phases of Engineering",
    content: `## The Engineering Process

### Before Code
Planning and design

### During Code
Development and validation

### After Code
Review and deployment`,
    type: "content",
  },

  {
    id: 19,
    title: "Before Code (Planning)",
    content: "",
    type: "section",
  },

  {
    id: 20,
    title: "PRD: Product Requirements Document",
    content: `## PRD - WHAT to Build

### Key Components
- **User Story** - Who needs what and why
- **Happy Path** - Ideal user journey
- **Edge Cases** - What can go wrong
- **Business View** - Success metrics and impact`,
    type: "content",
  },

  {
    id: 21,
    title: "RFC: Request for Comments",
    content: `## RFC - HOW to Build

### Technical Design
- **Technical Specification** - System behavior
- **Version** - API/schema versioning
- **Diagram Architecture** - Visual overview
- **Flowchart** - Process flows
- **Database Schema** - Data models
- **API Specification** - Endpoints and contracts
- **Test Cases** - Expected scenarios`,
    type: "content",
  },

  {
    id: 22,
    title: "During Code (Development)",
    content: "",
    type: "section",
  },

  {
    id: 23,
    title: "Planning Phase",
    content: `## Break Down the Work

### Development Planning
- Break down work based on PRD/RFC
- Plan implementation steps
- Identify dependencies
- Estimate complexity`,
    type: "content",
  },

  {
    id: 24,
    title: "AI Code Generation & Review",
    content: `## AI Writes Code

### The Process
1. **AI generates implementation** based on PRD/RFC
2. **Review changes immediately** after generation
3. **Catch issues early** in development loop
4. **Don't let AI slop accumulate**

*Continuous review is key!*`,
    type: "content",
  },

  {
    id: 25,
    title: "Engineering Metrics",
    content: `## Automated Quality Checks

### Continuous Validation
- **Test Coverage** - Unit and integration tests
- **E2E Test** - End-to-end scenarios
- **Readability** - Code maintainability
- **Security** - Vulnerability scanning
- **Performance** - Load and speed tests
- **Accessibility** - WCAG compliance`,
    type: "content",
  },

  {
    id: 26,
    title: "After Code (Pre-Production)",
    content: "",
    type: "section",
  },

  {
    id: 27,
    title: "MR Review Process",
    content: `## Human Review Gate

### Final Verification
- **Final human review** of all changes
- **Deeper context check** for business logic
- **Before merging to production**

This is where experience and judgment matter most.`,
    type: "content",
  },

  // ============================================================
  // AUTOMATION WITH AI
  // ============================================================
  {
    id: 28,
    title: "How to Improve This with AI?",
    content: "",
    type: "section",
  },

  {
    id: 29,
    title: "Agentic AI Can Help",
    content: `## The Opportunity

> "What if AI can automate the boring parts?
> 
> What if AI can help us follow these guardrails?
> 
> What tools make this easier?"`,
    type: "quote",
  },

  {
    id: 30,
    title: "Automation & Tools",
    content: "",
    type: "section",
  },

  {
    id: 31,
    title: "AI-Generated Documentation",
    content: `## Let AI Help with Docs

### PRD Generation
- AI generates from user requirements
- Human reviews and refines
- Faster than writing from scratch

### RFC Generation
- AI generates technical design from PRD
- Human validates architecture decisions
- AI helps visualize with diagrams`,
    type: "content",
  },

  {
    id: 32,
    title: "PRD Demo",
    content: "",
    type: "video",
    video: "https://drive.google.com/file/d/1HhF5WL_AWMhQmDLE9ta4zgklvwgAnMh_/preview",
  },

  {
    id: 33,
    title: "RFC Demo",
    content: "",
    type: "video",
    video: "https://drive.google.com/file/d/1GzYVJMNgQSoo1BRoZ8cBl2KTQPQf2fNq/preview",
  },

  {
    id: 34,
    title: "MCP: Model Context Protocol",
    content: `## Give AI Better Context

### What is MCP?
- Connect AI to external data sources
- Pull from GitHub/GitLab: tasks, issues, docs
- Give AI access to your actual project context

**AI makes better decisions with better context.**`,
    type: "content",
  },

  {
    id: 35,
    title: "Agent Skills",
    content: `## Reusable Knowledge Packages

### What are Agent Skills?
- Domain expertise packages (legal, data analysis)
- Company/team specific workflows
- Best practices and conventions

Skills teach AI your way of working.`,
    type: "content",
  },

  {
    id: 36,
    title: "AGENTS.md / Rules",
    content: `## Project-Specific Instructions

### Configuration for AI
- Build commands and setup steps
- Code style and conventions
- Testing procedures
- One file that works across all AI tools

Make AI follow your project standards automatically.`,
    type: "content",
  },

  {
    id: 37,
    title: "Work on Vibe",
    content: "",
    type: "video",
    video: "https://drive.google.com/file/d/1DNAJLFbXhQqeo5D-tEX_nCh2X-PnI1Cy/preview",
  },

  {
    id: 38,
    title: "PR Review Demo",
    content: "",
    type: "video",
    video: "https://drive.google.com/file/d/13dvsVTDx1Ie0CvbzcuIrpyvppKVihXGO/preview",
  },

  // ============================================================
  // CLOSING
  // ============================================================
  {
    id: 39,
    title: "Key Takeaways",
    content: "",
    type: "section",
  },

  {
    id: 40,
    title: "Remember This",
    content: `## Key Takeaways

- **AI Slop = Engineer Slop** (amplified)
- Problem is NOT the AI, it's **engineering culture**
- **Guardrails work** for both human and AI code
- AI can help **automate guardrails** (PRD/RFC generation)
- Give AI better context (**MCP, Skills, Rules**)
- **Engineering culture > Technology choice**`,
    type: "content",
  },

  {
    id: 41,
    title: "Ship Quality, Not Just Features",
    content: `## Conclusion

- Build **engineering culture first** (PRD/RFC/Reviews)
- Use **Agentic AI** to automate boring parts
- Give AI context with **MCP, Skills, and Rules**
- **Review everything** (human or AI generated)
- **Ship quality, not just features**

---

**Thank you!**`,
    type: "title",
  },
];

export function getSlide(id: number): Slide | undefined {
  return slides.find((s) => s.id === id);
}

export function getTotalSlides(): number {
  return slides.length;
}
